version: '3'

services:
    video_service:
        container_name: video_service
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
        - ./videos/:/videos/

        restart: always
        network_mode: "host"
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "3"

    postgres:
        image: postgres:13.3
        environment:
            POSTGRES_DB: "dev"
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "pass"
        ports:
            - "5432:5432"

    test_front:
        container_name: test_frot
        build:
            context: ./clientstream
            dockerfile: Dockerfile

        ports:
            - "3000:3000"